const RecommendationCard = ({ nextSteps = [], confidenceNotes = "" }) => {
  return (
    <div className="dashboard-panel p-6">
      <div className="mb-3">
        <div className="text-sm font-bold">Recommendations</div>
        <div className="text-xs uppercase tracking-[0.24em] text-slate-400">
          Next steps generated by AI
        </div>
      </div>

      <div className="grid gap-4 lg:grid-cols-3">
        <div className="lg:col-span-2">
          <ol className="space-y-2">
            {nextSteps.slice(0, 6).map((step, i) => (
              <li key={i} className="text-sm">
                {i + 1}. {step}
              </li>
            ))}
            {!nextSteps.length ? (
              <li className="text-sm text-slate-500">
                No recommendations yet.
              </li>
            ) : null}
          </ol>
        </div>

        <div>
          <div className="text-xs uppercase tracking-[0.24em] text-slate-400">
            Confidence
          </div>
          <div className="mt-2 text-sm text-slate-600 dark:text-slate-300">
            {confidenceNotes || ""}
          </div>
        </div>
      </div>
    </div>
  );
};

export default RecommendationCard;
